# Generated by Django 5.2.5 on 2025-09-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_cnic_user_contact_user_name_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
    ]
