# Generated by Django 5.2.5 on 2025-10-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_cgpa_student_previous_cgpa'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttransport',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='students.student'),
        ),
    ]
