# Generated by Django 5.2.5 on 2025-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='recipient_instructor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient_instructor',
        ),
        migrations.AlterField(
            model_name='call',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('CONNECTED', 'Connected'), ('ENDED', 'Ended'), ('FAILED', 'Failed')], default='INITIATED', max_length=20),
        ),
    ]
