# Generated by Django 5.2.5 on 2025-09-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_migrate_department_data'),
        ('messaging', '0002_remove_call_recipient_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='recipient_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_calls', to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='instructors.instructor'),
        ),
    ]
