# Generated by Django 5.2.5 on 2025-09-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('father_guardian', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('gpa', models.FloatField(default=0.0)),
                ('performance_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
