# Generated by Django 5.2.5 on 2025-09-10 06:13

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q

def copy_course_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Course = apps.get_model('academics', 'Course')
    
    # Copy course data to course_code before altering
    for student in Student.objects.all():
        if student.course:
            # If course is a string, try to find matching course
            if isinstance(student.course, str):
                try:
                    # Try to find course by name or code
                    course_obj = Course.objects.filter(
                        Q(name__icontains=student.course) | 
                        Q(code__icontains=student.course)
                    ).first()
                    if course_obj:
                        student.course_code = course_obj.code
                    else:
                        student.course_code = student.course
                except:
                    student.course_code = student.course
            else:
                student.course_code = str(student.course)
            student.save(update_fields=['course_code'])

class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_department_course_section'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(copy_course_data),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course'),
        ),
    ]
