# Generated by Django 5.2.5 on 2025-09-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_address_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_guardian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
