# Generated by Django 5.2.5 on 2025-09-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_course_department_semester_course_semester_and_more'),
        ('students', '0009_add_batch_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='academics.course'),
        ),
    ]
