# Generated by Django 5.2.5 on 2025-09-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_cgpa',
            field=models.FloatField(default=0.0),
        ),
    ]
