# Generated by Django 5.2.5 on 2025-09-14 09:46

import django.db.models.deletion
from django.db import migrations, models

def migrate_department_data_forward(apps, schema_editor):
    # Use raw SQL to update the data since the model field is still CharField during migration
    db_alias = schema_editor.connection.alias

    # Get all instructors with non-null department values
    instructors_with_departments = """
        SELECT id, department FROM instructors_instructor
        WHERE department IS NOT NULL AND department != ''
    """

    cursor = schema_editor.connection.cursor()
    cursor.execute(instructors_with_departments)
    instructors = cursor.fetchall()

    for instructor_id, department_name in instructors:
        # Find the corresponding department ID
        cursor.execute("""
            SELECT department_id FROM academics_department
            WHERE name = %s
        """, [department_name])

        department_result = cursor.fetchone()
        if department_result:
            department_id = department_result[0]
            # Update the instructor record with the department ID
            cursor.execute("""
                UPDATE instructors_instructor
                SET department = %s
                WHERE id = %s
            """, [department_id, instructor_id])

def migrate_department_data_reverse(apps, schema_editor):
    Instructor = apps.get_model('instructors', 'Instructor')

    for instructor in Instructor.objects.all():
        # Convert back to string for reverse migration
        if instructor.department:
            instructor.department = instructor.department.name
            instructor.save(update_fields=['department'])

class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_department_course_section'),
        ('instructors', '0002_instructor_image'),
    ]

    operations = [
        migrations.RunPython(migrate_department_data_forward, migrate_department_data_reverse),
        migrations.AlterField(
            model_name='instructor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
