# Generated by Django 5.2.5 on 2025-09-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_department_course_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
