# Generated by Django 5.2.5 on 2025-09-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_course_department_semester_course_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='num_semesters',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
