# Generated by Django 5.2.5 on 2025-09-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_result_course_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='department_fees',
                to='academics.department',
                null=True,
                blank=True
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE academics_fee
            SET department_id = (
                SELECT department_id
                FROM students_student
                WHERE students_student.student_id = academics_fee.student_id
            );
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
