# Generated by Django 5.2.5 on 2025-09-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_auto_20250924_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='term',
        ),
        migrations.AddField(
            model_name='fee',
            name='semester',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='semester_fees',
                to='academics.semester',
                null=True,
                blank=True
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE academics_fee
            SET semester_id = (
                SELECT semester_id
                FROM students_student
                WHERE students_student.student_id = academics_fee.student_id
            );
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
