# Generated by Django 5.2.5 on 2025-09-25 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_add_fee_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='fee_structure_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='obtained_marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_marks',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Cheque', 'Cheque')], default='Cash', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.fee')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
