# Generated by Django 5.2.5 on 2025-09-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_feestructure_fee_structure_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
