# Generated by Django 5.2.5 on 2025-09-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_add_quiz_marks'),
        ('students', '0012_student_cgpa_student_previous_cgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('gpa', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
